# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "318ace28f9da788f38afadd8339bb795"
name = "Click and Collect -OMF"
handle = "worklocker-1"
application_url = "https://click-n-collect-duplicate-work-db4f2d503a39.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "edible-bloom-shipping-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://click-n-collect-duplicate-work-db4f2d503a39.herokuapp.com/auth/callback",
  "https://click-n-collect-duplicate-work-db4f2d503a39.herokuapp.com/auth/shopify/callback",
  "https://click-n-collect-duplicate-work-db4f2d503a39.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
